<?php
echo showSectionHead($pluginText['Web Proxy']);
$actFun = SP_DEMO ? "alertDemoMsg()" : pluginConfirmPOSTMethod('projectform', 'subcontent', 'action=doWebProxy');
?>
<form id='projectform' onsubmit="<?php echo $actFun?>;return false;">
<table class="search" style="width: 80%">
	<tr>
		<th><?php echo $spText['common']['Server']?>:</th>
		<td>
			<select name="source_id" class="custom-select">
				<?php foreach($proxyList as $proxyInfo){?>
					<?php if($proxyInfo['id'] == $sourceId){?>
						<option value="<?php echo $proxyInfo['id']?>" selected><?php echo $proxyInfo['proxy']?></option>
					<?php }else{?>
						<option value="<?php echo $proxyInfo['id']?>"><?php echo $proxyInfo['proxy']?></option>
					<?php }?>
				<?php }?>
			</select>
		</td>
	</tr>
	<tr>
		<th><?php echo $spText['common']['Url']?>:*</th>
		<td>
			<input type="text" id="qwpUrlInput" name="url" value="<?php echo htmlspecialchars($post['url'] ?? '')?>" class="form-control">
		</td>
	</tr>
	<tr>
		<th>&nbsp;</th>
		<td>
			<a href="javascript:void(0);" onclick="<?php echo $actFun?>" class="btn btn-primary"><?php echo $spText['button']['Proceed']?></a>
			<?php if (!empty($localAiAvailable)) { ?>
			&nbsp;<button type="button" id="qwpAiSummaryBtn" class="btn btn-outline-primary" onclick="qwpSummarizeWithAI()">
				<i class="fas fa-magic"></i> Summarize with AI
			</button>
			<?php } ?>
		</td>
	</tr>
	<?php if (!empty($localAiAvailable)) { ?>
	<tr id="qwpAiSummaryRow" style="display:none;">
		<th>AI Summary:</th>
		<td>
			<div id="qwpAiSummaryText" class="alert alert-info" style="margin-bottom:0;"></div>
			<p>Generated by your on-premise Local AI (Ollama) from this page's own text - nothing is sent to a third party.</p>
		</td>
	</tr>
	<?php } ?>
</table>
</form>
<div id='subcontent'></div>
<?php if (!empty($localAiAvailable)) { ?>
<script type="text/javascript">
function qwpSummarizeWithAI() {
	var url = document.getElementById('qwpUrlInput').value;
	if (!url) {
		alert('Please enter a url first.');
		return;
	}
	var btn = document.getElementById('qwpAiSummaryBtn');
	var originalHtml = btn.innerHTML;
	btn.disabled = true;
	btn.innerHTML = '<i class="fas fa-spinner fa-spin"></i> Summarizing...';
	$.ajax({
		url: '<?php echo PLUGIN_SCRIPT_URL; ?>&action=summarizeWithAI',
		type: 'GET',
		data: { url: url },
		dataType: 'json',
		success: function(response) {
			document.getElementById('qwpAiSummaryRow').style.display = '';
			if (response.ok) {
				document.getElementById('qwpAiSummaryText').className = 'alert alert-info';
				document.getElementById('qwpAiSummaryText').innerText = response.summary;
			} else {
				document.getElementById('qwpAiSummaryText').className = 'alert alert-danger';
				document.getElementById('qwpAiSummaryText').innerText = response.error || 'Could not generate a summary.';
			}
		},
		error: function() {
			document.getElementById('qwpAiSummaryRow').style.display = '';
			document.getElementById('qwpAiSummaryText').className = 'alert alert-danger';
			document.getElementById('qwpAiSummaryText').innerText = 'Could not generate a summary.';
		},
		complete: function() {
			btn.disabled = false;
			btn.innerHTML = originalHtml;
		}
	});
}
</script>
<?php } ?>